// Generated by cggen

#import <dispatch/dispatch.h>

const void *CGGenCreateBytecodeStorage(const uint8_t *bytes, intptr_t count, intptr_t decompressedSize);
void CGGenDrawBytecode(CGContextRef context, const void *storage, intptr_t startIndex, intptr_t endIndex);
void CGGenApplyPathBytecode(CGMutablePathRef path, const void *storage, intptr_t startIndex, intptr_t endIndex);

static const uint8_t mergedBytecodes[53];

static const void *bytecodeStorage(void) {
  static const void *storage;
  static dispatch_once_t once;
  dispatch_once(&once, ^{
    storage = CGGenCreateBytecodeStorage(mergedBytecodes, 53, 41);
  });
  return storage;
}

void pdf_extgstate_determDrawExtgstateMultipleParamsImageInContext(CGContextRef context) {
  CGGenDrawBytecode(context, bytecodeStorage(), 0, 40);
}

static const uint8_t mergedBytecodes[] = {
  0x62, 0x76, 0x78, 0x2D, 0x29, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x22, 0x00, 0x00, 0x40, 0x3F, 0x25, 0x00, 0x00,
  0x00, 0x3F, 0x24, 0x7F, 0x7F, 0x7F, 0x06, 0x00, 0x00, 0xA0, 0x41, 0x00,
  0x00, 0xA0, 0x41, 0x00, 0x00, 0x20, 0x43, 0x00, 0x00, 0x20, 0x43, 0x13,
  0x00, 0x62, 0x76, 0x78, 0x24
};
